

# website

baseurl: /fast-pypi-release
url: https://nvfp.github.io/fast-pypi-release


# personal

title: fast-pypi-release
author:
  name: Nicholas Valentinus


# internal

include: [_pages, _sass, scripts]

permalink: pretty

sass:
  style: compact # possible values: nested expanded compact compressed
  sass_dir: _sass
